version: '3'
services:
  frontend:
    image: frontend:v1
    ports:
      - "5501:80"
    depends_on:
      - backend
    networks:
      - deploy

  backend:
    image: backend:v1
    ports:
      - "8000:8000"
    networks:
      - deploy

networks:
  deploy:
    driver: bridge